=== GeekNickson/CrossPlatformIntegrationLabs/DTD-XML-Schema-lab1/schema.dtd
<!ELEMENT root (doctors*, specialties*, services*, patients*)*>
<!ELEMENT doctors (doctor*)>
<!ELEMENT specialties (specialty*)>
<!ELEMENT services (service*)>
<!ELEMENT patients (patient*)>
<!ELEMENT patient (first_name, last_name, age)>
<!ELEMENT doctor (first_name, last_name, age, category, experience,  vacation_start, vacation_end)>
<!ELEMENT specialty ( name )>
<!ELEMENT service ( name )>
<!ELEMENT name ( #PCDATA )>
<!ELEMENT price ( #PCDATA )>
<!ELEMENT first_name ( #PCDATA )>
<!ELEMENT last_name ( #PCDATA )>
<!ELEMENT age ( #PCDATA )>
<!ELEMENT vacation_start ( #PCDATA )>
<!ELEMENT vacation_end ( #PCDATA )>
<!ELEMENT day ( #PCDATA )>
<!ELEMENT category ( #PCDATA )>
<!ELEMENT experience ( #PCDATA )>
<!ATTLIST specialty id ID #REQUIRED>
<!ATTLIST service id ID #REQUIRED>
<!ATTLIST service price CDATA #REQUIRED>
<!ATTLIST doctor id ID #REQUIRED>
<!ATTLIST schedule id ID #REQUIRED>
<!ATTLIST doctor specialty_id IDREF #REQUIRED>
<!ATTLIST doctor services IDREFS #IMPLIED>
<!ATTLIST service type CDATA "%default_service">
<!ATTLIST root href CDATA #REQUIRED>
<!ENTITY first "Первая">
<!ENTITY second "Вторая">
<!ENTITY third "Третья">
<!ENTITY phd "Высшая">
<!ENTITY % default_service "therapy">
<!ENTITY home_link SYSTEM "https://ispi.cdo.vlsu.ru/">

=== GeekNickson/CrossPlatformIntegrationLabs/DTD-XML-Schema-lab1/dtd_example.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE root SYSTEM "schema.dtd">

<root href="home_link">
  <doctors>
    <doctor id="eugene" specialty_id="neurology" services="diagnostic treatment">
      <first_name>Евгений</first_name>
      <last_name>Гений</last_name>
      <age>25</age>
      <category>&first;</category>
      <experience>1</experience>
      <vacation_start>2021-06-01</vacation_start>
      <vacation_end>2021-06-30</vacation_end>
    </doctor>
  </doctors>
  <services>
    <service id="diagnostic" price="1500">
      <name>Диагностика</name>
    </service>
    <service id="treatment" price="1500">
      <name>Лечение</name>
    </service>
  </services>
  <specialties>
    <specialty id="neurology">
      <name>Неврология</name>
    </specialty>
  </specialties>
  <patients></patients>
</root>
